networks:
  famiphoto_network:
services:
  famiphoto:
    image: famiphoto
    container_name: famiphoto
    build:
      context: .
      dockerfile: docker/famiphoto/Dockerfile
      target: prod
    ports:
      - 8080:8080
    volumes:
      - ${CONTENTS_DIR}:/mnt/famiphoto
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
  elasticsearch:
    build:
      context: .
      dockerfile: docker/search/Dockerfile
    container_name: elasticsearch
    restart: always
    networks:
      - famiphoto_network
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - "xpack.security.enabled=false"
  mysql:
    image: mysql:8.0
    container_name: famiphoto_mysqldb
    platform: linux/amd64
    restart: always
    env_file:
      - .env.options.local
    volumes:
      - ./schema/dbschema/generator/:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306
    networks:
      - famiphoto_network
  redis_oauth:
    image: redis:7.4
    container_name: redis_oauth
    networks:
      - famiphoto_network
