networks:
  famiphoto_network:
services:
  famiphoto:
    image: famiphoto
    container_name: famiphoto
    build:
      context: .
      dockerfile: docker/famiphoto/Dockerfile
      target: local
    ports:
      - 7002:8080
    networks:
      - famiphoto_network
    tty: true
    command: air -c ./.air/.air.toml
    env_file:
      - .env
    volumes:
      - ./:/go/src/github.com/hiroyky/famiphoto/
      - ${CONTENTS_DIR}:/mnt/famiphoto
  elasticsearch:
    build:
      context: .
      dockerfile: docker/search/Dockerfile
    #image: docker.elastic.co/elasticsearch/elasticsearch:8.1.3
    container_name: elasticsearch
    restart: always
    networks:
      - famiphoto_network
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - "xpack.security.enabled=false"
  kibana:
    image: docker.elastic.co/kibana/kibana:8.1.3
    container_name: kibana
    networks:
      - famiphoto_network
    #ports:
    #  - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
  mysql:
    image: mysql:8.0
    container_name: famiphoto_mysqldb
    platform: linux/amd64
    restart: always
    env_file:
      - .env
    volumes:
      - ./schema/dbschema/generator/:/docker-entrypoint-initdb.d/
    ports:
      - 7001:3306
    networks:
      - famiphoto_network
  redis_oauth:
    image: redis:6.2
    container_name: redis_oauth
    platform: linux/amd64
    networks:
      - famiphoto_network
