version: '3.3'
networks:
  famiphoto_network:
services:
  famiphoto:
    image: famiphoto
    container_name: famiphoto_api
    build:
      context: .
      dockerfile: docker/famiphoto/Dockerfile
    networks:
      - famiphoto_network
    env_file:
      - .env.local
    volumes:
      - ./home/famiphoto:/mnt/famiphoto
    depends_on:
      - mysql
  famiphoto_web:
    container_name: famiphoto_web
    image: famiphoto_web
    build:
      context: github.com/hiroyky/famiphoto_web.git#main
    env_file:
      - dst/.env.web.prod
    ports:
      - 3000:3000
    networks:
      - famiphoto_network
  elasticsearch:
    build:
      context: .
      dockerfile: docker/search/Dockerfile
    container_name: elasticsearch
    restart: always
    networks:
      - famiphoto_network
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - "xpack.security.enabled=false"
  kibana:
    image: docker.elastic.co/kibana/kibana:8.1.3
    container_name: kibana
    networks:
      - famiphoto_network
    #ports:
    #  - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
  mysql:
    image: mysql:8.0
    container_name: famiphoto_mysqldb
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./schema/dbschema/generator/:/docker-entrypoint-initdb.d/
    networks:
      - famiphoto_network
    ports:
      - 7001:3306
  redis_oauth:
    image: redis:6.2
    container_name: redis_oauth
    platform: linux/amd64
    networks:
      - famiphoto_network