# start docker containers
networks:
  famiphoto_network:
services:
  api:
    depends_on:
      - mysql
    image: famiphoto_api
    container_name: famiphoto_api
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - 8080:8080
    networks:
      - famiphoto_network
    tty: true
    env_file:
      - .env
    volumes:
      - ${CONTENTS_DIR}:/mnt/famiphoto
  web:
    image: famiphoto_web
    container_name: famiphoto_web
    build: 
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - 3000:3000
    networks:
      - famiphoto_network
    tty: true
    env_file:
      - .env
  elasticsearch:
    build:
      context: .
      dockerfile: docker/elasticsearch/Dockerfile
    #image: docker.elastic.co/elasticsearch/elasticsearch:8.1.3
    container_name: elasticsearch
    restart: always
    networks:
      - famiphoto_network
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - "xpack.security.enabled=false"
  mysql:
    image: mysql:8
    container_name: famiphoto_mysqldb
    restart: always
    env_file:
      - .env
    volumes:
      - ./mysql/dbschema/generator/:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306
    networks:
      - famiphoto_network
  redis_session:
    image: redis:6.2
    container_name: redis_session
    platform: linux/amd64
    networks:
      - famiphoto_network
