// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces/http/graph/model/models_gen.go

// Package mock_model is a generated GoMock package.
package mock_model

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/hiroyky/famiphoto/interfaces/http/graph/model"
)

// MockConnection is a mock of Connection interface.
type MockConnection struct {
	ctrl     *gomock.Controller
	recorder *MockConnectionMockRecorder
}

// MockConnectionMockRecorder is the mock recorder for MockConnection.
type MockConnectionMockRecorder struct {
	mock *MockConnection
}

// NewMockConnection creates a new mock instance.
func NewMockConnection(ctrl *gomock.Controller) *MockConnection {
	mock := &MockConnection{ctrl: ctrl}
	mock.recorder = &MockConnectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnection) EXPECT() *MockConnectionMockRecorder {
	return m.recorder
}

// GetEdges mocks base method.
func (m *MockConnection) GetEdges() []model.Edge {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEdges")
	ret0, _ := ret[0].([]model.Edge)
	return ret0
}

// GetEdges indicates an expected call of GetEdges.
func (mr *MockConnectionMockRecorder) GetEdges() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEdges", reflect.TypeOf((*MockConnection)(nil).GetEdges))
}

// GetNodes mocks base method.
func (m *MockConnection) GetNodes() []model.Node {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodes")
	ret0, _ := ret[0].([]model.Node)
	return ret0
}

// GetNodes indicates an expected call of GetNodes.
func (mr *MockConnectionMockRecorder) GetNodes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodes", reflect.TypeOf((*MockConnection)(nil).GetNodes))
}

// GetPageInfo mocks base method.
func (m *MockConnection) GetPageInfo() *model.PageInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPageInfo")
	ret0, _ := ret[0].(*model.PageInfo)
	return ret0
}

// GetPageInfo indicates an expected call of GetPageInfo.
func (mr *MockConnectionMockRecorder) GetPageInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPageInfo", reflect.TypeOf((*MockConnection)(nil).GetPageInfo))
}

// IsConnection mocks base method.
func (m *MockConnection) IsConnection() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IsConnection")
}

// IsConnection indicates an expected call of IsConnection.
func (mr *MockConnectionMockRecorder) IsConnection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsConnection", reflect.TypeOf((*MockConnection)(nil).IsConnection))
}

// MockEdge is a mock of Edge interface.
type MockEdge struct {
	ctrl     *gomock.Controller
	recorder *MockEdgeMockRecorder
}

// MockEdgeMockRecorder is the mock recorder for MockEdge.
type MockEdgeMockRecorder struct {
	mock *MockEdge
}

// NewMockEdge creates a new mock instance.
func NewMockEdge(ctrl *gomock.Controller) *MockEdge {
	mock := &MockEdge{ctrl: ctrl}
	mock.recorder = &MockEdgeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEdge) EXPECT() *MockEdgeMockRecorder {
	return m.recorder
}

// GetCursor mocks base method.
func (m *MockEdge) GetCursor() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCursor")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetCursor indicates an expected call of GetCursor.
func (mr *MockEdgeMockRecorder) GetCursor() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCursor", reflect.TypeOf((*MockEdge)(nil).GetCursor))
}

// GetNode mocks base method.
func (m *MockEdge) GetNode() model.Node {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNode")
	ret0, _ := ret[0].(model.Node)
	return ret0
}

// GetNode indicates an expected call of GetNode.
func (mr *MockEdgeMockRecorder) GetNode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNode", reflect.TypeOf((*MockEdge)(nil).GetNode))
}

// IsEdge mocks base method.
func (m *MockEdge) IsEdge() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IsEdge")
}

// IsEdge indicates an expected call of IsEdge.
func (mr *MockEdgeMockRecorder) IsEdge() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEdge", reflect.TypeOf((*MockEdge)(nil).IsEdge))
}

// MockNode is a mock of Node interface.
type MockNode struct {
	ctrl     *gomock.Controller
	recorder *MockNodeMockRecorder
}

// MockNodeMockRecorder is the mock recorder for MockNode.
type MockNodeMockRecorder struct {
	mock *MockNode
}

// NewMockNode creates a new mock instance.
func NewMockNode(ctrl *gomock.Controller) *MockNode {
	mock := &MockNode{ctrl: ctrl}
	mock.recorder = &MockNodeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNode) EXPECT() *MockNodeMockRecorder {
	return m.recorder
}

// GetID mocks base method.
func (m *MockNode) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockNodeMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockNode)(nil).GetID))
}

// IsNode mocks base method.
func (m *MockNode) IsNode() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IsNode")
}

// IsNode indicates an expected call of IsNode.
func (mr *MockNodeMockRecorder) IsNode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsNode", reflect.TypeOf((*MockNode)(nil).IsNode))
}

// MockPagination is a mock of Pagination interface.
type MockPagination struct {
	ctrl     *gomock.Controller
	recorder *MockPaginationMockRecorder
}

// MockPaginationMockRecorder is the mock recorder for MockPagination.
type MockPaginationMockRecorder struct {
	mock *MockPagination
}

// NewMockPagination creates a new mock instance.
func NewMockPagination(ctrl *gomock.Controller) *MockPagination {
	mock := &MockPagination{ctrl: ctrl}
	mock.recorder = &MockPaginationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPagination) EXPECT() *MockPaginationMockRecorder {
	return m.recorder
}

// GetNodes mocks base method.
func (m *MockPagination) GetNodes() []model.Node {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodes")
	ret0, _ := ret[0].([]model.Node)
	return ret0
}

// GetNodes indicates an expected call of GetNodes.
func (mr *MockPaginationMockRecorder) GetNodes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodes", reflect.TypeOf((*MockPagination)(nil).GetNodes))
}

// GetPageInfo mocks base method.
func (m *MockPagination) GetPageInfo() *model.PaginationInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPageInfo")
	ret0, _ := ret[0].(*model.PaginationInfo)
	return ret0
}

// GetPageInfo indicates an expected call of GetPageInfo.
func (mr *MockPaginationMockRecorder) GetPageInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPageInfo", reflect.TypeOf((*MockPagination)(nil).GetPageInfo))
}

// IsPagination mocks base method.
func (m *MockPagination) IsPagination() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IsPagination")
}

// IsPagination indicates an expected call of IsPagination.
func (mr *MockPaginationMockRecorder) IsPagination() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsPagination", reflect.TypeOf((*MockPagination)(nil).IsPagination))
}
