// Code generated by MockGen. DO NOT EDIT.
// Source: usecases/search_usecase.go

// Package mock_usecases is a generated GoMock package.
package mock_usecases

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSearchUseCase is a mock of SearchUseCase interface.
type MockSearchUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockSearchUseCaseMockRecorder
}

// MockSearchUseCaseMockRecorder is the mock recorder for MockSearchUseCase.
type MockSearchUseCaseMockRecorder struct {
	mock *MockSearchUseCase
}

// NewMockSearchUseCase creates a new mock instance.
func NewMockSearchUseCase(ctrl *gomock.Controller) *MockSearchUseCase {
	mock := &MockSearchUseCase{ctrl: ctrl}
	mock.recorder = &MockSearchUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchUseCase) EXPECT() *MockSearchUseCaseMockRecorder {
	return m.recorder
}

// AppendAllPhotoDocuments mocks base method.
func (m *MockSearchUseCase) AppendAllPhotoDocuments(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendAllPhotoDocuments", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendAllPhotoDocuments indicates an expected call of AppendAllPhotoDocuments.
func (mr *MockSearchUseCaseMockRecorder) AppendAllPhotoDocuments(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendAllPhotoDocuments", reflect.TypeOf((*MockSearchUseCase)(nil).AppendAllPhotoDocuments), ctx)
}
