// Code generated by MockGen. DO NOT EDIT.
// Source: infrastructures/repositories/group_repository.go

// Package mock_repositories is a generated GoMock package.
package mock_repositories

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	dbmodels "github.com/hiroyky/famiphoto/infrastructures/dbmodels"
)

// MockGroupRepository is a mock of GroupRepository interface.
type MockGroupRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGroupRepositoryMockRecorder
}

// MockGroupRepositoryMockRecorder is the mock recorder for MockGroupRepository.
type MockGroupRepositoryMockRecorder struct {
	mock *MockGroupRepository
}

// NewMockGroupRepository creates a new mock instance.
func NewMockGroupRepository(ctrl *gomock.Controller) *MockGroupRepository {
	mock := &MockGroupRepository{ctrl: ctrl}
	mock.recorder = &MockGroupRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroupRepository) EXPECT() *MockGroupRepositoryMockRecorder {
	return m.recorder
}

// CountUsersByGroupID mocks base method.
func (m *MockGroupRepository) CountUsersByGroupID(ctx context.Context, groupID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUsersByGroupID", ctx, groupID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUsersByGroupID indicates an expected call of CountUsersByGroupID.
func (mr *MockGroupRepositoryMockRecorder) CountUsersByGroupID(ctx, groupID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUsersByGroupID", reflect.TypeOf((*MockGroupRepository)(nil).CountUsersByGroupID), ctx, groupID)
}

// ExistGroup mocks base method.
func (m *MockGroupRepository) ExistGroup(ctx context.Context, groupID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistGroup", ctx, groupID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistGroup indicates an expected call of ExistGroup.
func (mr *MockGroupRepositoryMockRecorder) ExistGroup(ctx, groupID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistGroup", reflect.TypeOf((*MockGroupRepository)(nil).ExistGroup), ctx, groupID)
}

// ExistGroupUser mocks base method.
func (m *MockGroupRepository) ExistGroupUser(ctx context.Context, groupID, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistGroupUser", ctx, groupID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistGroupUser indicates an expected call of ExistGroupUser.
func (mr *MockGroupRepositoryMockRecorder) ExistGroupUser(ctx, groupID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistGroupUser", reflect.TypeOf((*MockGroupRepository)(nil).ExistGroupUser), ctx, groupID, userID)
}

// GetGroup mocks base method.
func (m *MockGroupRepository) GetGroup(ctx context.Context, groupID string) (*dbmodels.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroup", ctx, groupID)
	ret0, _ := ret[0].(*dbmodels.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroup indicates an expected call of GetGroup.
func (mr *MockGroupRepositoryMockRecorder) GetGroup(ctx, groupID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroup", reflect.TypeOf((*MockGroupRepository)(nil).GetGroup), ctx, groupID)
}

// GetGroupsByUserID mocks base method.
func (m *MockGroupRepository) GetGroupsByUserID(ctx context.Context, userID string) (dbmodels.GroupSlice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupsByUserID", ctx, userID)
	ret0, _ := ret[0].(dbmodels.GroupSlice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupsByUserID indicates an expected call of GetGroupsByUserID.
func (mr *MockGroupRepositoryMockRecorder) GetGroupsByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupsByUserID", reflect.TypeOf((*MockGroupRepository)(nil).GetGroupsByUserID), ctx, userID)
}

// GetUsersByGroupID mocks base method.
func (m *MockGroupRepository) GetUsersByGroupID(ctx context.Context, groupID string, limit, offset int) (dbmodels.UserSlice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersByGroupID", ctx, groupID, limit, offset)
	ret0, _ := ret[0].(dbmodels.UserSlice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersByGroupID indicates an expected call of GetUsersByGroupID.
func (mr *MockGroupRepositoryMockRecorder) GetUsersByGroupID(ctx, groupID, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersByGroupID", reflect.TypeOf((*MockGroupRepository)(nil).GetUsersByGroupID), ctx, groupID, limit, offset)
}
