// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/hiroyky/famiphoto/drivers/mysql"
	"github.com/hiroyky/famiphoto/infrastructures/repositories"
	"github.com/hiroyky/famiphoto/usecases"
)

// Injectors from wire.go:

func InitUserUseCase() usecases.UserUseCase {
	sqlExecutor := mysql.NewDatabaseDriver()
	userAdapter := repositories.NewUserRepository(sqlExecutor)
	userUseCase := usecases.NewUserUseCase(userAdapter)
	return userUseCase
}
