// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/hiroyky/famiphoto/drivers/mysql"
	"github.com/hiroyky/famiphoto/infrastructures/repositories"
	"github.com/hiroyky/famiphoto/interfaces/http/graph"
	"github.com/hiroyky/famiphoto/services"
	"github.com/hiroyky/famiphoto/usecases"
)

// Injectors from wire.go:

func InitResolver() *graph.Resolver {
	sqlExecutor := mysql.NewDatabaseDriver()
	userAdapter := repositories.NewUserRepository(sqlExecutor)
	passwordService := services.NewPasswordService()
	userUseCase := usecases.NewUserUseCase(userAdapter, passwordService)
	oauthClientAdapter := repositories.NewOauthClientRepository(sqlExecutor)
	oauthUseClientCase := usecases.NewOauthUseCase(oauthClientAdapter, passwordService)
	resolver := graph.NewResolver(userUseCase, oauthUseClientCase)
	return resolver
}
